project_id = "tithbqxdoaegpnwnqtej"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
port = 54324
tenant_id = "realtime-dev"
encryption_key = "supabase_realtime_dev"

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54321
file_size_limit = "50MiB"

[auth]
enabled = true
port = 54321
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true
email_double_confirm_changes = true
enable_anonymous_sign_ins = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.sms]
enable_signup = true
enable_confirmations = false

[[auth.sms.twilio]]
enabled = false
account_sid = ""
message_service_sid = ""

[[auth.sms.twilio_verify]]
enabled = false
account_sid = ""
message_service_sid = ""

[[auth.sms.messagebird]]
enabled = false
originator = ""

[[auth.sms.textlocal]]
enabled = false
sender = ""

[[auth.sms.vonage]]
enabled = false
from = ""

[functions.analyze-plant]
verify_jwt = false