// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tithbqxdoaegpnwnqtej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpdGhicXhkb2FlZ3Bud25xdGVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNjk2MzgsImV4cCI6MjA2OTY0NTYzOH0.OrHqr21go-z4Yk2j9RKs3BfGA3Mw2gQezrge4XZnmIY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});